# "cursor.style" = "Block"
import = ["/home/mmarfeychuk/.config/alacritty/themes/themes/palenight.toml"]
live_config_reload = true
# "mouse.hide_when_typing" = false
# "window.dynamic_title" = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
# family = "CaskaydiaCove Nerd Font"
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font"
family = "FiraCode Nerd Font"
style = "Medium"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 6

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "Full"

[window.dimensions]
columns = 160
lines = 36
